# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CatalystX-CRUD-Model-DBIC
version:      0.03
version_from: lib/CatalystX/CRUD/Model/DBIC.pm
installdirs:  site
requires:
    Catalyst::Model::DBIC::Schema: 0
    CatalystX::CRUD:               0.25
    DBIx::Class:                   0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
